#ifndef IRQ_H
#define IRQ_H

#define NVIC_PRIORITY_GROUPING	3	// 4+0 bits

#define NVIC_PRIORITY_MATRIX	1
#define NVIC_PRIORITY_USB	2
#define NVIC_PRIORITY_SYSTICK	3
#define NVIC_PRIORITY_I2C	6

#endif // IRQ_H
